### ISSUE TITLE
Fail deploying to Heroku

### ISSUE THREAD

**Issue by if1y** [Aid-3n/URL-UPLOADER-TG#4]
```
-----> ffmpeg app detected
-----> Install ffmpeg
       DOWNLOAD_URL =  https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
       exporting PATH
-----> p7zip app detected
-----> Fetching and vendoring p7zip
       Using p7zip version: 9.20.1
-----> Python app detected
 !     Python has released a security update! Please consider upgrading to python-3.7.9
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.7.2
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting git+git://github.com/google/chatbase-python.git (from -r /tmp/build_a12fa262_/requirements.txt (line 3))
         Cloning git://github.com/google/chatbase-python.git to /tmp/pip-req-build-u55sxgue
         Running command git clone -q git://github.com/google/chatbase-python.git /tmp/pip-req-build-u55sxgue
       Collecting https://github.com/prgofficial/pyrogram (from -r /tmp/build_a12fa262_/requirements.txt (line 7))
         Downloading https://github.com/prgofficial/pyrogram
         ERROR: Cannot unpack file /tmp/pip-unpack-v630s2l9/pyrogram (downloaded from /tmp/pip-req-build-ai7uh05z, content-type: text/html; charset=utf-8); cannot detect archive format
       ERROR: Cannot determine archive format of /tmp/pip-req-build-ai7uh05z
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by 4nuu** [comment]
Try Now.. Requirements Has Been Edited💔😪

**Comment by prabha-coder** [comment]
How to get a chat base token?

**Comment by 4nuu** [comment]
Just Leave Any Values Such Ad xD Or Zz Anything,Proper Value Is Not Required Just Use Some Alternative 😅 Meanwhile You Can Use https://chatbase.com/

**Comment by if1y** [comment]
> Try Now.. Requirements Has Been Edited💔😪

Deploy successfully now.
But still no response while sending msg to bot... (All input values correct) 😢

**Comment by prabha-coder** [comment]
https://github.com/prabha-coder/URLuploader-With-Hotstar <-- this repo is working. Dear Aid-3n, can you fix it with this repo?

**Comment by 4nuu** [comment]
@prabha-coder Then You Could Use That Repo,Right?

**Comment by prabha-coder** [comment]
Dear @Aid-3n, There is a problem with Hotstar URL. it would be great if you fixed it and implement the Hotstar feature with our bot repo. Thank you for your kind response.

**Comment by EagleScou** [comment]
-----> Building on the Heroku-20 stack
-----> ffmpeg app detected
-----> Install ffmpeg
       DOWNLOAD_URL =  https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
       exporting PATH
-----> p7zip app detected
-----> Fetching and vendoring p7zip
       Using p7zip version: 9.20.1
-----> Python app detected
 !     Requested runtime (python-3.7.2) is not available for this stack (heroku-20).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by EagleScou** [comment]
Getting this error please help 
deploying in heroku

**Comment by 4nuu** [comment]
TRY Again Or Change Python Version to 3.9.0
